### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by NRD90M** [LiangNiang/fake-world#12]
PS E:\Codes\fake-world> pnpm install
Lockfile is up to date, resolution step is skipped
Packages: +674
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 674, reused 673, downloaded 0, added 0, done
node_modules/.pnpm/@prisma+engines@5.9.1/node_modules/@prisma/engines: Running postinstall script...
node_modules/.pnpm/bun@1.0.29/node_modules/bun: Running postinstall script, failed in 127ms
.../.pnpm/bun@1.0.29/node_modules/bun postinstall$ node install.js
│ Error: Unsupported platform: win32 x64
│     at E:\Codes\fake-world\node_modules\.pnpm\bun@1.0.29\node_modules\bun\install.js:304:13
│     at Generator.next (<anonymous>)
│     at E:\Codes\fake-world\node_modules\.pnpm\bun@1.0.29\node_modules\bun\install.js:40:59
│     at new Promise (<anonymous>)
│     at __async (E:\Codes\fake-world\node_modules\.pnpm\bun@1.0.29\node_modules\bun\install.js:26:51)
│     at importBun (E:\Codes\fake-world\node_modules\.pnpm\bun@1.0.29\node_modules\bun\install.js:302:10)
│     at Object.<anonymous> (E:\Codes\fake-world\node_modules\.pnpm\bun@1.0.29\node_modules\bun\install.js:424:1)
│     at Module._compile (node:internal/modules/cjs/loader:1369:14)
│     at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
│     at Module.load (node:internal/modules/cjs/loader:1206:32)
└─ Failed in 127ms at E:\Codes\fake-world\node_modules\.pnpm\bun@1.0.29\node_modules\bun
 ELIFECYCLE  Command failed with exit code 1.

**Comment by NRD90M** [comment]
PS E:\Codes\fake-world> pnpm run dev:ewb
 ERR_PNPM_NO_SCRIPT  Missing script: dev:ewb

Command "dev:ewb" not found. Did you mean "pnpm run dev:web"?

**Comment by LiangNiang** [comment]
文档里面的有 Typos，应该是pnpm run dev:web，也可以 cd packages/web && pnpm run dev
