### ISSUE TITLE
功能不可用

### ISSUE THREAD

**Issue by ppswws** [LiangNiang/fake-world#16]
聊天框里的红包转账以及图片语音等都不可以点击呢
能出一个没有控制和编辑的版本吗？

**Comment by LiangNiang** [comment]
您好，点击红包、播放语音，并没有考虑做更下层的交互，毕竟用作截图够了，图片、视频点击放大预览这个可以我准备做一下。没有编辑的功能指的是只有中间那块纯粹的微信界面吗，这个也没考虑支持，您可以考虑 fork 二次开发或者欢迎提 PR

**Comment by 13eieve** [comment]
<img width="906" alt="image" src="https://github.com/user-attachments/assets/404235db-1c1a-49b3-b784-91834945af45">
我只启动前端，一直启动不了
